services:
  - type: web
    name: frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "/api"
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://backend:8000/$1
    plan: free

  - type: web
    name: backend
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm run start:prod
    plan: free
